[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "16"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Configuraci贸n para producci贸n
[context.production]
  command = "npm run build"
  environment = { VITE_API_URL = "https://api.tuapp.com", VITE_ENV = "production" }

# Configuraci贸n para vistas previas de pull requests
[context.deploy-preview]
  command = "npm run build"
  environment = { VITE_API_URL = "https://api-staging.tuapp.com", VITE_ENV = "staging" }

# Configuraci贸n para la rama develop
[context.branch-deploy]
  command = "npm run build"
  environment = { VITE_API_URL = "https://api-branch.tuapp.com", VITE_ENV = "branch" }
