[build]
  publish = "dist"
  command = "npm run build"

# Configuración para despliegues automáticos de pull requests
[context.deploy-preview]
  command = "npm run build"

# Configuración para ramas específicas
[context.branch-deploy]
  command = "npm run build"
  environment = { NODE_VERSION = "16" }

# Variables de entorno para diferentes contextos
[context.production.environment]
  VITE_API_URL = "https://api.tuapp.com"

[context.deploy-preview.environment]
  VITE_API_URL = "https://api-staging.tuapp.com"
