[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "16"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  VITE_API_URL = "https://api.tuapp.com"
  VITE_ENV = "production"

[context.deploy-preview.environment]
  VITE_API_URL = "https://api-staging.tuapp.com"
  VITE_ENV = "staging"

[context.branch-deploy.environment]
  VITE_API_URL = "https://api-branch.tuapp.com"
  VITE_ENV = "branch"
